---
require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

Layout/ClassStructure:
  Enabled: true

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Layout/LineLength:
  Max: 120

Lint/DeprecatedOpenSSLConstant:
  Enabled: true

Lint/MixedRegexpCaptureTypes:
  Enabled: true

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Migration/DepartmentName:
  Enabled: true

Style/CollectionMethods:
  Enabled: true

Style/ConstantVisibility:
  Enabled: true

Style/Documentation:
  Enabled: false

Style/ExponentialNotation:
  Enabled: true

Style/HashEachMethods:
  Enabled: true

Style/ImplicitRuntimeError:
  Enabled: true

Style/InlineComment:
  Enabled: true
  Exclude:
    - config/boot.rb

Style/MethodCallWithArgsParentheses:
  Enabled: false

Style/ReturnNil:
  Enabled: true

Style/Send:
  Enabled: true

Style/StringHashKeys:
  Enabled: true
  Exclude:
    - config/environments/*.rb

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/RedundantRegexpCharacterClass:
  Enabled: true

Style/RedundantRegexpEscape:
  Enabled: true

Style/SlicingWithRange:
  Enabled: true

AllCops:
  TargetRubyVersion: 2.7
  DisplayCopNames: true
  Exclude:
    - 'bin/*'
    - 'engines/**/*'
    - 'db/schema.rb'
    - 'db/migrate/*.rb'
